[package]
name = "actix-web"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "3"
serde = "1"
serde_json = "1"
serde_derive = "1"
diesel = { version = "1.4.8", features = ["sqlite", "r2d2"] }
dotenv = "0.15.0"
chrono = "0.4.19"
uuid = {version = "0.8.2", features = ["serde", "v4"]}
